"use client";
import { Bell, CheckCheck, ChevronDown, FileText, LogOut, Menu, Search, Settings } from "lucide-react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { User } from "@/types/auth";
import { clearAuth } from "@/lib/auth";
import api from "@/lib/api";
import Sidebar from "./Sidebar";

export default function Header({ user }: { user: User }) {
  const [open, setOpen] = useState(false), [profileOpen, setProfileOpen] = useState(false), [search, setSearch] = useState("");
  const router = useRouter(), profileRef = useRef<HTMLDivElement>(null);
  const client = useQueryClient();
  const notifications = useQuery({ queryKey: ["notifications"], queryFn: async () => (await api.get<NotificationsResponse>("/notifications")).data, refetchInterval: 30_000 });
  const readOne = useMutation({ mutationFn: (id: string) => api.put(`/notifications/${id}/read`), onSuccess: () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  const readAll = useMutation({ mutationFn: () => api.put("/notifications/read-all"), onSuccess: () => client.invalidateQueries({ queryKey: ["notifications"] }) });
  useEffect(() => { const close = (event: MouseEvent) => { if (!profileRef.current?.contains(event.target as Node)) setProfileOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const logout = async () => { try { await api.post("/auth/logout"); } finally { clearAuth(); router.replace("/login"); } };
  return <><header className="flex h-[68px] items-center justify-between gap-5 border-b border-slate-200 bg-white px-4 shadow-sm sm:px-6 lg:px-8"><div className="flex shrink-0 items-center gap-3"><button onClick={() => setOpen(true)} className="rounded-lg p-2 hover:bg-slate-100 md:hidden" aria-label="Open navigation"><Menu size={20} /></button><h2 className="text-base font-bold text-slate-950 sm:text-lg">RFQ Management System</h2></div><form onSubmit={(e) => { e.preventDefault(); if (search.trim()) { sessionStorage.setItem("rfq-search", search.trim()); router.push("/rfqs"); } }} className="relative hidden max-w-md flex-1 lg:block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-100" placeholder="Search RFQs, customers…" /></form><div className="flex items-center gap-1"><NotificationDropdown data={notifications.data} onRead={(id) => readOne.mutate(id)} onReadAll={() => readAll.mutate()} /><div ref={profileRef} className="relative"><button onClick={() => setProfileOpen((value) => !value)} className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-white px-3 py-2 shadow-sm transition hover:bg-slate-50"><span className="grid size-12 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-blue-800 text-sm font-bold text-white shadow-sm">{user.name.charAt(0).toUpperCase()}</span><span className="hidden text-left sm:block"><strong className="block text-sm text-slate-900">{user.name}</strong><small className="block text-xs text-slate-500">{user.role === "admin" ? "Administrator" : "Team Member"}</small></span><ChevronDown size={16} className={`text-slate-500 transition ${profileOpen ? "rotate-180" : ""}`} /></button>{profileOpen && <div className="absolute right-0 top-[calc(100%+10px)] z-50 w-52 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl"><div className="border-b px-3 py-2.5"><p className="truncate text-sm font-semibold">{user.name}</p><p className="truncate text-xs text-slate-500">{user.email}</p></div><button onClick={() => { setProfileOpen(false); router.push("/settings"); }} className="mt-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-slate-50"><Settings size={16} />Settings</button><button onClick={logout} className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm text-red-600 hover:bg-red-50"><LogOut size={16} />Log out</button></div>}</div></div></header>{open && <><button aria-label="Close navigation" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-slate-950/40 md:hidden" /><Sidebar user={user} open onClose={() => setOpen(false)} /></>}</>;
}

type NotificationItem = { _id: string; title: string; message: string; isRead: boolean; createdAt: string; rfq?: { _id: string; rfqNumber: string } };
type NotificationsResponse = { data: NotificationItem[]; unread: number };
function NotificationDropdown({ data, onRead, onReadAll }: { data?: NotificationsResponse; onRead: (id: string) => void; onReadAll: () => void }) { const [open, setOpen] = useState(false); return <div className="relative"><button onClick={() => setOpen((v) => !v)} className="grid size-10 place-items-center rounded-xl text-slate-600 hover:bg-slate-100" aria-label="Open notifications"><Bell size={20} /></button>{data && data.unread > 0 && <span className="absolute right-1 top-1 grid size-4 place-items-center rounded-full bg-blue-600 text-[10px] font-bold text-white">{data.unread > 9 ? "9+" : data.unread}</span>}{open && <div className="absolute right-0 top-12 z-50 w-[360px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b px-4 py-3"><div><p className="font-semibold">Notifications</p><p className="text-xs text-slate-500">{data?.unread || 0} unread</p></div><button onClick={onReadAll} disabled={!data?.unread} className="flex items-center gap-1 text-xs font-semibold text-blue-600 disabled:opacity-40"><CheckCheck size={15} />Mark all read</button></div><div className="max-h-96 overflow-y-auto">{data?.data.length ? data.data.map((item) => <Link href={item.rfq ? `/rfqs/${item.rfq._id}` : "/dashboard"} key={item._id} onClick={() => { if (!item.isRead) onRead(item._id); setOpen(false); }} className={`flex gap-3 border-b px-4 py-3 last:border-0 hover:bg-slate-50 ${item.isRead ? "" : "bg-blue-50/50"}`}><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-blue-100 text-blue-600"><FileText size={16} /></span><span className="min-w-0"><strong className="block text-sm">{item.title}</strong><span className="mt-0.5 block text-xs text-slate-500">{item.message}</span><small className="mt-1 block text-[11px] text-slate-400">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</small></span></Link>) : <p className="p-8 text-center text-sm text-slate-500">No notifications yet.</p>}</div></div>}</div>; }
