"use client";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Plus, Search } from "lucide-react";
import { useState } from "react";
import RFQTable from "@/components/rfq/RFQTable";
import api from "@/lib/api";
import { apiMessage } from "@/lib/auth";
import type { User } from "@/types/auth";
import type { RFQ, RFQListResponse } from "@/types/rfq";
import { notify } from "@/lib/notification";

export default function RFQsPage() {
  const client = useQueryClient();
  const [search, setSearch] = useState(() => { if (typeof window === "undefined") return ""; const value = sessionStorage.getItem("rfq-search") || ""; sessionStorage.removeItem("rfq-search"); return value; }), [status, setStatus] = useState(""), [assignedTo, setAssignedTo] = useState(""), [page, setPage] = useState(1);
  const me = useQuery({ queryKey: ["me"], queryFn: async () => (await api.get<{ data: User }>("/auth/me")).data.data });
  const users = useQuery({ queryKey: ["users"], queryFn: async () => (await api.get<{ data: User[] }>("/users")).data.data });
  const query = useQuery({ queryKey: ["rfqs", { search, status, assignedTo, page }], queryFn: async () => (await api.get<RFQListResponse>("/rfqs", { params: { search: search || undefined, status: status || undefined, assignedTo: assignedTo || undefined, page, limit: 10 } })).data });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/rfqs/${id}`), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["rfqs"] }); await client.invalidateQueries({ queryKey: ["dashboard"] }); notify("RFQ deleted successfully"); } });
  const update = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setter(event.target.value); setPage(1); };
  const onDelete = (rfq: RFQ) => { if (window.confirm(`Delete ${rfq.rfqNumber}? This action cannot be undone.`)) remove.mutate(rfq._id); };
  const exportCsv = async () => { try { const result = (await api.get<RFQListResponse>("/rfqs", { params: { search: search || undefined, status: status || undefined, assignedTo: assignedTo || undefined, limit: 1000 } })).data.data; const cell = (v: string) => `"${v.replaceAll('"', '""')}"`; const rows = [["RFQ Number", "RFQ Date", "Customer", "Contact Person", "Email", "Subject", "Assigned To", "Status", "Submission Date", "Prepared By"], ...result.map((r) => [r.rfqNumber, r.rfqDate.slice(0, 10), r.customer, r.contactPerson, r.email, r.subject, r.assignedTo.name, r.status, r.submissionDate?.slice(0, 10) || "", r.preparedBy?.name || ""])]; const blob = new Blob(["\uFEFF" + rows.map((row) => row.map(cell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `rfqs-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); notify("CSV exported successfully"); } catch { notify("Unable to export CSV", "error"); } };
  return <div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-blue-100 bg-gradient-to-r from-white to-blue-50 px-6 py-6 shadow-sm"><div><p className="text-sm font-medium text-blue-600">Quotation requests</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">RFQs</h1><p className="mt-2 text-slate-500">Search, filter, and manage quotation requests.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold hover:bg-slate-50"><Download size={17} />Export CSV</button>{me.data?.role === "admin" && <Link href="/rfqs/new" className="flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white shadow-sm hover:bg-blue-700"><Plus size={17} />New RFQ</Link>}</div></div>
    <div className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_220px]"><label className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input value={search} onChange={update(setSearch)} className="input pl-9" placeholder="Search number, customer or subject" /></label><select value={status} onChange={update(setStatus)} className="select"><option value="">All statuses</option><option>Pending</option><option>Waiting Supplier Quotation</option><option>Submitted</option></select><select value={assignedTo} onChange={update(setAssignedTo)} className="select"><option value="">All assignees</option>{users.data?.map((u) => <option key={u._id} value={u._id}>{u.name}</option>)}</select></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{query.isPending ? <State text="Loading RFQs…" /> : query.isError ? <State text="Unable to load RFQs." /> : query.data.data.length ? <><RFQTable rfqs={query.data.data} user={me.data} onDelete={onDelete} /><div className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4 text-sm"><p className="text-slate-500">{query.data.pagination.total} RFQ{query.data.pagination.total === 1 ? "" : "s"}</p><Pagination page={page} pages={query.data.pagination.pages} setPage={setPage} /></div></> : <State text="No RFQs match your filters." />}</section>{remove.isError && <p className="mt-3 text-sm text-red-600">{apiMessage(remove.error, "Unable to delete RFQ")}</p>}</div>;
}
function State({ text }: { text: string }) { return <div className="p-14 text-center text-sm text-slate-500">{text}</div>; }
function Pagination({ page, pages, setPage }: { page: number; pages: number; setPage: React.Dispatch<React.SetStateAction<number>> }) { const visible = Array.from({ length: pages }, (_, i) => i + 1).filter((n) => n === 1 || n === pages || Math.abs(n - page) <= 2); return <div className="flex items-center gap-1"><button disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button>{visible.map((n, i) => <span key={n} className="flex items-center">{i > 0 && n - visible[i - 1] > 1 && <span className="px-1 text-slate-400">…</span>}<button onClick={() => setPage(n)} className={`size-8 rounded-lg ${n === page ? "bg-slate-950 text-white" : "border"}`}>{n}</button></span>)}<button disabled={page >= pages} onClick={() => setPage((p) => p + 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div>; }
