"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { BarChart3, CheckCircle2, Clock3, FileText, Plus, Truck } from "lucide-react";
import api from "@/lib/api";
import StatusBadge from "@/components/rfq/StatusBadge";
import type { User } from "@/types/auth";
import type { RFQ } from "@/types/rfq";

interface DashboardData { stats: { total: number; pending: number; waiting: number; submitted: number }; recent: RFQ[]; monthly: { month: string; count: number }[]; }
const formatDate = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "2-digit", year: "numeric" }).format(new Date(value));
export default function DashboardPage() {
  const query = useQuery({ queryKey: ["dashboard"], queryFn: async () => (await api.get<{ data: DashboardData }>("/dashboard/stats")).data.data });
  const me = useQuery({ queryKey: ["me"], queryFn: async () => (await api.get<{ data: User }>("/auth/me")).data.data });
  if (query.isError) return <State text="Could not load dashboard data." />;
  if (query.isPending) return <State text="Loading dashboard…" />;
  const { stats, recent, monthly } = query.data;
  const cards = [{ label: "Total RFQs", value: stats.total, icon: FileText, style: "bg-blue-50 text-blue-600", color: "#2563eb" }, { label: "Pending", value: stats.pending, icon: Clock3, style: "bg-amber-50 text-amber-600", color: "#f59e0b" }, { label: "Waiting Supplier", value: stats.waiting, icon: Truck, style: "bg-violet-50 text-violet-600", color: "#8b5cf6" }, { label: "Submitted", value: stats.submitted, icon: CheckCircle2, style: "bg-emerald-50 text-emerald-600", color: "#10b981" }];
  return <div className="mx-auto max-w-[1450px]"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-slate-500">Overview</p><h1 className="text-3xl font-bold tracking-tight text-slate-950">Dashboard</h1><p className="mt-1 text-slate-500">Track requests, assignments, and quotation progress.</p></div>{me.data?.role === "admin" && <Link href="/rfqs/new" className="flex h-12 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700"><Plus size={19} />New RFQ</Link>}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, style, color }) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className={`grid size-14 place-items-center rounded-2xl ${style}`}><Icon size={25} /></span><div><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-1 text-3xl font-bold text-slate-950">{value}</p></div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${stats.total ? Math.max(8, Math.round(value / stats.total * 100)) : 0}%`, backgroundColor: color }} /></div></div>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-700"><FileText size={19} /></span><div><h2 className="font-semibold">Recent RFQs</h2><p className="text-sm text-slate-500">Latest quotation requests</p></div></div><Link href="/rfqs" className="text-sm font-semibold text-blue-600">View all →</Link></div>{recent.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="bg-slate-50 text-xs uppercase text-slate-500"><th className="px-5 py-3">RFQ</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">RFQ Date</th><th className="px-5 py-3">Assigned</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y">{recent.map((rfq) => <tr key={rfq._id} className="hover:bg-slate-50"><td className="px-5 py-4"><Link className="font-semibold text-blue-600" href={`/rfqs/${rfq._id}`}>{rfq.rfqNumber}</Link></td><td className="px-5 py-4 font-medium">{rfq.customer}</td><td className="px-5 py-4 text-slate-500">{formatDate(rfq.rfqDate)}</td><td className="px-5 py-4 text-slate-600">{rfq.assignedTo.name}</td><td className="px-5 py-4"><StatusBadge status={rfq.status} /></td></tr>)}</tbody></table></div> : <State text="No RFQs yet." />}</section>
      <div className="grid gap-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><BarChart3 className="text-blue-600" size={21} /><div><h2 className="font-semibold">RFQ activity</h2><p className="text-sm text-slate-500">RFQs registered over the last 6 months</p></div></div><ActivityChart data={monthly} /></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5"><h2 className="font-semibold">Status overview</h2><p className="text-sm text-slate-500">Live distribution of RFQs by status</p></div><StatusChart stats={stats} /></section></div></div>
  </div>;
}
function ActivityChart({ data }: { data: { month: string; count: number }[] }) { const max = Math.max(...data.map((d) => d.count), 1); const points = data.map((d, i) => `${10 + i * 18},${74 - d.count / max * 58}`).join(" "); return <div><svg viewBox="0 0 100 82" className="h-40 w-full overflow-visible" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2563eb" stopOpacity=".28" /><stop offset="1" stopColor="#2563eb" stopOpacity="0" /></linearGradient></defs>{[16, 35, 54, 74].map((y) => <line key={y} x1="8" x2="98" y1={y} y2={y} stroke="#e2e8f0" strokeWidth=".5" />)}<polygon points={`10,74 ${points} 100,74`} fill="url(#area)" /><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="2" vectorEffect="non-scaling-stroke" />{data.map((d, i) => <circle key={d.month} cx={10 + i * 18} cy={74 - d.count / max * 58} r="1.7" fill="#2563eb" />)}</svg><div className="grid grid-cols-6 text-center text-xs text-slate-500">{data.map((d) => <span key={d.month}>{d.month}</span>)}</div></div>; }
function StatusChart({ stats }: { stats: DashboardData["stats"] }) { const total = stats.total || 1, p = stats.pending / total * 100, w = stats.waiting / total * 100; const rows = [{ label: "Pending", value: stats.pending, color: "bg-amber-400" }, { label: "Waiting Supplier", value: stats.waiting, color: "bg-violet-500" }, { label: "Submitted", value: stats.submitted, color: "bg-emerald-500" }]; return <div className="flex items-center gap-7"><div className="relative grid size-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#fbbf24 0 ${p}%, #8b5cf6 ${p}% ${p + w}%, #10b981 ${p + w}% 100%)` }}><div className="grid size-20 place-items-center rounded-full bg-white text-center"><span><strong className="block text-2xl">{stats.total}</strong><small className="text-slate-500">Total RFQs</small></span></div></div><div className="flex-1 space-y-3">{rows.map((row) => <div key={row.label} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><i className={`size-2.5 rounded-full ${row.color}`} />{row.label}</span><span className="font-semibold">{row.value} <span className="ml-1 text-xs font-normal text-slate-500">{Math.round(row.value / total * 100)}%</span></span></div>)}</div></div>; }
function State({ text }: { text: string }) { return <div className="rounded-2xl border bg-white p-12 text-center text-sm text-slate-500">{text}</div>; }
